[project]
name = "nailed-it"
version = "0.0.0"
description = "Perfection? 💯 Chaos? 🤡; Harry's AI AgentOps Environment."
readme = "README.md"
requires-python = ">=3.14"

[dependency-groups]
dev = ["pyrefly>=1.0.0", "ruff>=0.15.12"]

[tool.uv.workspace]
members = ["python-packages/*"]

[tool.ruff]
include = [
    "pyproject.toml",
    "python-packages/*/pyproject.toml",
    "python-packages/*/src/**/*.py",
    "python-packages/*/tests/**/*.py",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Formatter compatibility.
    # See https://docs.astral.sh/ruff/rules/missing-trailing-comma/#formatter-compatibility
    "COM812",
    # Formatter compatibility.
    # See https://docs.astral.sh/ruff/rules/incorrect-blank-line-before-class/#formatter-compatibility
    "D203",
    # Google convention compatibility.
    # See https://docs.astral.sh/ruff/rules/multi-line-summary-second-line/
    "D213",
]

[tool.pyrefly]
project-includes = [
    "python-packages/*/src/**/*.py",
    "python-packages/*/tests/**/*.py",
]
