model_list:
  - model_name: mimo-v2.5-pro-precision
    litellm_params:
      model: openai/mimo-v2.5-pro-precision
      api_base: https://crof.ai/v1
      api_key: os.environ/CROF_API_KEY

litellm_settings:
  callbacks: ["arize_phoenix", "force_temp_callback.proxy_handler_instance"]

environment_variables:
  PHOENIX_COLLECTOR_HTTP_ENDPOINT: http://localhost:6006/v1/traces
  PHOENIX_PROJECT_NAME: hindsight
